spring:
  application:
    name: SmartHouse
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_db
    username: home_admin
    password: home123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    com.example.SmartHouse: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# Добавленные строки
JWT_ACCESS_COOKIE_NAME: access_token
JWT_REFRESH_COOKIE_NAME: refresh_token
JWT_ACCESS_TOKEN_DURATION_MINUTE: 15
JWT_ACCESS_TOKEN_DURATION_SECOND: 900
JWT_REFRESH_TOKEN_DURATION_DAY: 7
JWT_REFRESH_TOKEN_DURATION_SECOND: 604800

telegram:
  bot-token: 'YOUR_TELEGRAM_BOT_TOKEN'
  chat-id: 'YOUR_CHAT_ID'